services:
  # NGINX Web Server
  nginx:
    image: nginx:alpine
    container_name: web-server
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app

  # PHP Application
  php-app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php-container
    volumes:
      - ./www:/var/www/html