services:
  # NGINX Web Server
  nginx:
    build: ./docker/nginx
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./hello:/var/www/html
    depends_on:
      - php
    networks:
      - laravel-network

  # PHP-FPM for Laravel
  php:
    build: ./docker/php
    container_name: laravel-php
    volumes:
      - ./hello:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel-network

  # MySQL Database (Custom Build)
  mysql:
    build: ./docker/mysql          # Use custom Dockerfile instead of official image
    container_name: laravel-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Database initialization
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
